apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-login
  template:
    metadata:
      labels:
        app: react-login
    spec:
      containers:
        - name: react-login
          image: yourdockerhubusername/react-login-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-login-service
spec:
  type: NodePort
  selector:
    app: react-login
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
